from django.db import models
from django.utils import timezone
import datetime

#家长问卷
class B_RT(models.Model):
    PopulationID = models.CharField(max_length = 100,blank=True,primary_key=True)
    name = models.CharField(max_length = 100,blank=True)
    checkYear = models.CharField(max_length = 100,blank=True,default="N")
    checkMonth = models.CharField(max_length = 100,blank=True,default="N")
    checkDay = models.CharField(max_length = 100,blank=True,default="N")
    checherID = models.CharField(max_length = 100,blank=True,default="9")
    B_RT_Q1 = models.CharField(max_length = 100,blank=True,default="9")
    B_RT_Q2 = models.CharField(max_length = 100,blank=True,default="N")
    B_RT_Q3 = models.CharField(max_length = 100,blank=True,default="9")
    B_RT_Q4a = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q4b = models.CharField(max_length=100, blank=True,default="9")
    B_RT_Q4c = models.CharField(max_length=100, blank=True,default="9")
    B_RT_Q5 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q6 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q7 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q8 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q9 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q10 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q11 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q12 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q13 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q14 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q15 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q16 = models.CharField(max_length=100,blank=True,default="N")
    B_RT_Q17 = models.CharField(max_length=100,blank=True,default="N")
    B_RT_Q18 = models.CharField(max_length=100,blank=True,default="99")
    B_RT_Q19 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q20 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q21a = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q21b = models.CharField(max_length=100, blank=True,default="9")
    B_RT_Q21c = models.CharField(max_length=100, blank=True,default="9")
    B_RT_Q21d = models.CharField(max_length=100, blank=True,default="9")
    B_RT_Q21e = models.CharField(max_length=100, blank=True,default="9")
    B_RT_Q21f = models.CharField(max_length=100, blank=True,default="9")
    B_RT_Q22a = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q22b = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q22c = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q22d = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q22e = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q22f = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q22g = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q22h = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q23 = models.CharField(max_length=100,blank=True,default="9")
    B_RT_Q24 = models.CharField(max_length=100,blank=True,default="N")
    B_RT_Q25 = models.CharField(max_length=100,blank=True,default="N")

    def __unicode__(self):
        return self.PopulationID

 #学生问卷
class B_XS(models.Model):
    PopulationID = models.CharField(max_length = 100,blank=True,primary_key=True)
    name = models.CharField(max_length=100, blank=True)
    school = models.CharField(max_length=100, blank=True)
    grade = models.CharField(max_length=100, blank=True)
    classes = models.CharField(max_length=100, blank=True)
    checkYear = models.CharField(max_length = 100,blank=True,default="N")
    checkMonth = models.CharField(max_length = 100,blank=True,default="N")
    checkDay = models.CharField(max_length = 100,blank=True,default="N")
    checherID = models.CharField(max_length = 100,blank=True,default="9")
    B_XS_Q1 = models.CharField(max_length = 100,blank=True,default="9")
    B_XS_Q2 = models.CharField(max_length = 100,blank=True,default="9")
    B_XS_Q3 = models.CharField(max_length = 100,blank=True,default="9")
    B_XS_Q4 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q5 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q6 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q7 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q8 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q9a = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q9b = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q9c = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q10 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q11 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q12 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q13 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q14 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q15 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q16 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q17 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q18 = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q19a = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q19b = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q19c = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q19d = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q19e = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q19f = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q19g = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q19h = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q20a = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q20b = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q20c = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q20d = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21a = models.CharField(max_length=100,blank=True,default="9")
    B_XS_Q21b = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21c = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21d = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21e = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21f = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21g = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21h = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q21i = models.CharField(max_length=100, blank=True,default="9")
    B_XS_Q22 = models.CharField(max_length=100,blank=True,default="N")

    def __unicode__(self):
        return self.PopulationID

#成人问卷
class B_CR(models.Model):
    PopulationID = models.CharField(max_length=100, blank=True,primary_key=True)
    name = models.CharField(max_length=100, blank=True)
    checkYear = models.CharField(max_length=100, blank=True,default="N")
    checkMonth = models.CharField(max_length=100, blank=True,default="N")
    checkDay = models.CharField(max_length=100, blank=True,default="N")
    checherID = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q1 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q2a = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q2b = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q2c = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q3 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q4 = models.CharField(max_length=100, blank=True,default="N")
    B_CR_Q5 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q6 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q7a = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q7b = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q7c = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q8 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q9 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q10 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q11 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q12 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q13 = models.CharField(max_length=100, blank=True,default="N")
    B_CR_Q14 = models.CharField(max_length=100, blank=True,default="N")
    B_CR_Q15 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q16 = models.CharField(max_length=100, blank=True,default="99")
    B_CR_Q17a = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q17b = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q17c = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q17d = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q17e = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q18 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q19 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20a = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20b = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20c = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20d = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20e = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20f = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20g = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20h = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20i = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20j = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20k = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q20l = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q21 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q22 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q23a = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q23b = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q23c = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q23d = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24a = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24b = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24c = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24d = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24e = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24f = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24g = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q24h = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q25 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q25_6 = models.CharField(max_length=100, blank=True,default="9")
    B_CR_Q26 = models.CharField(max_length=100, blank=True,default="N")
    B_CR_Q27 = models.CharField(max_length=100, blank=True,default="N")


    def __unicode__(self):
        return self.PopulationID
